name: Continuous Integration

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de tu rama principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Puedes cambiar esto si tu aplicación usa una versión diferente de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Asegúrate de tener un archivo requirements.txt con las dependencias de tu aplicación

    - name: Run unit tests
      run: |
        python -m unittest  # Esto ejecutará todas las pruebas unitarias encontradas en tu proyecto

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to production
      run: |
        # Agrega aquí los comandos necesarios para desplegar tu aplicación en producción
